version: '2'
services:
  alarmo:
    image: antirek/speech-cacher:19.07.1
    command: speech-cacher
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=test
      - NODE_CONFIG_DIR=/etc/speech-cacher
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/:/etc/alarmo"
      - "/var/speech-cacher:/tmp/store"
    restart: always